# Generated by Django 5.2 on 2025-04-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='reserved_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
