# Generated by Django 5.2 on 2025-04-20 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='notified',
            field=models.BooleanField(default=False),
        ),
    ]
