# Generated by Django 5.2 on 2025-04-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_reservation_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='condition',
            field=models.CharField(blank=True, choices=[('good', 'Good'), ('damaged', 'Damaged'), ('lost', 'Lost')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='borrowrecord',
            name='fine',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
