# Generated by Django 5.2 on 2025-04-20 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_borrowrecord_condition_alter_borrowrecord_fine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone',
        ),
    ]
